spring:
  application:
    name: Jclinical

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jclinical}
    username: ${SPRING_DATASOURCE_USERNAME:jclinical}
    password: ${SPRING_DATASOURCE_PASSWORD:jclinical}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}